image: node:8

cache:
    paths:
        - node_modules/

stages:
    - build

build_job:
    stage: build
    script:
        - npm install
        - cd common
        - npm install
        - cd ../client
        - npm install
        - cd ../db
        - npm install
        - cd ../executor
        - npm install
        - cd ../server
        - npm install
