stages:
    - build
    - test

build_job:
    - stage: build
    - script:
        - npm install
        - node ./node_modules/gulp/bin/gulp.js

test_job:
    - stage: test
    - script:
        - ./node_modules/mocha/bin/mocha dist/app/tests
