image: node:8

cache:
    paths:
        - node_modules/

stages:
    - build
    - test

build_job:
    stage: build
    script:
        - npm install
        - node ./node_modules/gulp/bin/gulp.js
        - cd public
        - npm install
        - node ./node_modules/webpack/bin/webpack.js
        - cd ..

test_job:
    stage: test
    script:
        - ./node_modules/mocha/bin/mocha dist/app/tests
